const CONSTANTS = {
    LAYOUT1: {
        bgColor: "#fff",
        T_1: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "55px",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_2: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_3: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        SET_1: {
            TI_1: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            TI_2: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            TI_3: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            TI_4: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            TI_5: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
        },
    },
    LAYOUT2: {
        bgColor: "#fff",
        T_1: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        I_2: {
            bgColor: null,
            img: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_3: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        SET_1: {
            T_1: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_2: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_3: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_4: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_5: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_6: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_7: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_8: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_9: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_10: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_11: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            T_12: {
                bgColor: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
        },
    },
    LAYOUT3: {
        bgColor: "#fff",
        T_1: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        I_2: {
            bgColor: null,
            img: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_3: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_4: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_5: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
    },
    LAYOUT4: {
        bgColor: "#fff",
        T_1: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        SET_1: {
            I_1: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_2: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_3: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_4: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
        },
        SET_2: {
            V_1: {
                bgColor: null,
                url: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            V_2: {
                bgColor: null,
                url: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            V_3: {
                bgColor: null,
                url: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            V_4: {
                bgColor: null,
                url: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
        },
    },
    LAYOUT5: {
        bgColor: "#fff",
        T_1: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        SET_1: {
            I_1: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_2: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_3: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
            I_4: {
                bgColor: null,
                img: null,
                text: "",
                font: "NanumGothic",
                fontSize: "",
                fontColor: "#000",
                align: "center",
                bold: false,
                link: "",
            },
        },
    },
    LAYOUT6: {
        bgColor: "#fff",
        V_1: {
            bgColor: null,
            url: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
        T_2: {
            bgColor: null,
            text: "",
            font: "NanumGothic",
            fontSize: "",
            fontColor: "#000",
            align: "center",
            bold: false,
            link: "",
        },
    },
};

export default CONSTANTS;
